/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bank.EmprestimoBeneficiaio;
import com.mycompany.bank.CadastroBeneficiario.Conexao;
import com.mycompany.bank.PortalPrincipal.TelaPrincipal;
import com.mycompany.bank.EmprestimoBeneficiaio.Movimento;
import java.util.HashSet;
import javax.swing.JFrame;
import java.sql.Connection;// Banco DE DADOS
import java.sql.PreparedStatement;// BANCO DE DADOS 
import java.sql.ResultSet;
import java.sql.SQLException;// BANCO DE DADOS
import javax.swing.JOptionPane;
/**
 *
 * @author wladyson
 */
public class EmprestimoCliente extends javax.swing.JFrame {
    private TelaPrincipal TelaPrincipal;// Declare a referência para a TelaPrincipal
    /**
     * Creates new form EmprestimoCliente
     */
    public EmprestimoCliente() {
        
        this.TelaPrincipal = TelaPrincipal;// declara a referencia da tela principal
        
        initComponents();
        
        try {
    // Cria o MaskFormatter para data no formato "dd/MM/yyyy"
    javax.swing.text.MaskFormatter maskFormatter = new javax.swing.text.MaskFormatter("####-##-##");
    maskFormatter.setPlaceholderCharacter('_'); // Caractere usado para preencher
    jFormattedTextFieldDat.setFormatterFactory(
        new javax.swing.text.DefaultFormatterFactory(maskFormatter)
    );
    } catch (java.text.ParseException ex) {
    ex.printStackTrace();
    }
    try {
    // Cria o MaskFormatter para data no formato "dd/MM/yyyy" 
    javax.swing.text.MaskFormatter maskFormatter = new javax.swing.text.MaskFormatter("####-##-##");
    maskFormatter.setPlaceholderCharacter('_'); 
    jFormattedTextFieldDate.setFormatterFactory(
        new javax.swing.text.DefaultFormatterFactory(maskFormatter)
    );
    } catch (java.text.ParseException ex) {
    ex.printStackTrace();
    }    
    try {
    // Cria o MaskFormatter para data no formato "dd/MM/yyyy" 
    javax.swing.text.MaskFormatter maskFormatter = new javax.swing.text.MaskFormatter("####-##-##");
    maskFormatter.setPlaceholderCharacter('_'); 
    jFormattedTextFieldVenc.setFormatterFactory(
        new javax.swing.text.DefaultFormatterFactory(maskFormatter)
    );
    } catch (java.text.ParseException ex) {
    ex.printStackTrace();
    }    
    try {
    // Cria o MaskFormatter para data no formato "dd/MM/yyyy"
    javax.swing.text.MaskFormatter maskFormatter = new javax.swing.text.MaskFormatter("####-##-##");
    maskFormatter.setPlaceholderCharacter('_'); 
    jFormattedTextFieldDta.setFormatterFactory(
        new javax.swing.text.DefaultFormatterFactory(maskFormatter)
    );
    } catch (java.text.ParseException ex) {
    ex.printStackTrace();
    } 
        this.setLocationRelativeTo(null);//deixa centralizada no meio da tela
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);//deixa a tela maximizada
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnSaindo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDta = new javax.swing.JFormattedTextField();
        BtnPesquisa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtUN = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtControle = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtOperacao = new javax.swing.JTextField();
        CboTipo = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtQuantia = new javax.swing.JTextField();
        txtJuros = new javax.swing.JTextField();
        txtMulta = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtCredito = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtMora = new javax.swing.JTextField();
        txtCapital = new javax.swing.JTextField();
        txtLucros = new javax.swing.JTextField();
        txtTaxas = new javax.swing.JTextField();
        txtCET = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRenda = new javax.swing.JTextField();
        txtLimite = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIOF = new javax.swing.JTextField();
        txtCapitalizacao = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPagavel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CboTipoConta = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        Cbostatus = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        txtSAC = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtAvalista = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        CboFase = new javax.swing.JComboBox<>();
        CboParcelas = new javax.swing.JComboBox<>();
        CboMargem = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPObs = new javax.swing.JTextPane();
        lblNomeCliente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCarencia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CboSituacao = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtPrazos = new javax.swing.JTextField();
        jFormattedTextFieldDat = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDate = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        txtIndice = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        CboPeridiocidade = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtValores = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jFormattedTextFieldVenc = new javax.swing.JFormattedTextField();
        jLabel42 = new javax.swing.JLabel();
        CboFormPg = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        CboDivida = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        CboConciliacao = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        CboVigStatus = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPObsVig = new javax.swing.JTextPane();
        BtnCancela = new javax.swing.JButton();
        BtnSalva = new javax.swing.JButton();
        BtnRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emprestimo_Cliente_Contrato_Bancario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Emprestimo/Financiamento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        BtnSaindo.setBackground(new java.awt.Color(51, 102, 255));
        BtnSaindo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnSaindo.setForeground(new java.awt.Color(255, 255, 255));
        BtnSaindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_saida.png"))); // NOI18N
        BtnSaindo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSaindo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSaindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaindoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSaindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 30, 50, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel3.setText("Dt.Nascimento:");

        BtnPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_pesquisa.png"))); // NOI18N
        BtnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisaActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome:");

        jLabel5.setText("CPF:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldDta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPesquisa)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldDta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 920, 90));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Painel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel20.setText("U.N:");

        jLabel21.setText("Controle:");

        jLabel23.setText("Operaçao:");

        jLabel24.setText("Tipo:");

        CboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoa Física", "Pessoa Jurídica", "Cliente Corporativo", "Cliente de Alta Renda", "Cliente Varejo", "Cliente Institucional", "Cliente Governamental", "Cliente Não Residente", "Outros" }));

        jLabel25.setText("Quantia:");

        jLabel26.setText("Parcelas:");

        jLabel27.setText("Juros:");

        jLabel28.setText("Multa:");

        jLabel30.setText("Credito:");

        jLabel31.setText("Taxas:");

        jLabel32.setText("CET:");

        jLabel33.setText("Mora:");

        jLabel34.setText("Capital:");

        jLabel35.setText("Lucros:");

        jLabel36.setText("Capitalizaçao:");

        jLabel9.setText("Renda:");

        jLabel10.setText("Limite:");

        jLabel11.setText("IOF:");

        jLabel12.setText("Margem:");

        jLabel14.setText("Pagavel:");

        jLabel15.setText("Codigo:");

        jLabel16.setText("Tipo Conta:");

        CboTipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta Corrente", "Conta Poupança", "Conta Salário", "Conta Digital", "Conta Universitária", "Conta Conjunta", "Conta Empresarial", "Conta de Investimentos", "Conta Internacional", "Conta de Pagamento ", "Outras" }));

        jLabel29.setText("Status:");

        Cbostatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concluído", "Autorizado", "Liberado", "Aceito", "Confirmado", "Regularizado", "Válido", "Processado", "Ativo", "Efetivado", "Pendente", "Atrasado", "Negado", "Suspenso", "Cancelado", "Bloqueado", "Rejeitado", "Inadimplente", "Não Processado", "Inativo" }));

        jLabel37.setText("SAC:");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Cliente:");

        jLabel39.setText("Avalista:");

        jLabel40.setText("Fase;");

        CboFase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em Análise", "Sob Avaliação", "Aguardando Pagamento", "Em Negociação", "Liquidado", "Quitado", "Parcialmente Quitado", "Renegociado", "Em Andamento", "Finalizado", "Aprovado com Restrições", "Pré-Aprovado", "Expirado", "Arquivado", "Devolvido", " ", " ", " " }));

        CboParcelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "x1 parcelas", "x2 parcelas ", "x5 parcelas", "x10 parcelas", "x15 parcelas", "x20 parcelas", "x30 parcelas", "x40 parcelas", "x50 parcelas", "x60 parcelas" }));

        CboMargem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Margem Consignável", "Margem Bruta", "Margem Líquida", "Margem Excedente", "Margem de Risco", "Margem de Segurança" }));

        jLabel41.setText("OBS:");

        jScrollPane1.setViewportView(txtPObs);

        lblNomeCliente.setBackground(new java.awt.Color(153, 153, 153));
        lblNomeCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeCliente.setOpaque(true);
        lblNomeCliente.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblNomeClienteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRenda)
                            .addComponent(CboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLimite))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUN)
                            .addComponent(txtControle)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE)))))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CboMargem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIOF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CboParcelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQuantia)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtJuros)))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtCredito))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLucros))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCapital))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTaxas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtCET, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMora)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPagavel)
                    .addComponent(txtCapitalizacao)
                    .addComponent(txtCodigo)
                    .addComponent(CboTipoConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cbostatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSAC))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAvalista, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CboFase, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(txtUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(txtQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(jLabel36)
                        .addComponent(txtCapitalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38))
                    .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel26)
                    .addComponent(jLabel31)
                    .addComponent(txtTaxas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtPagavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(txtAvalista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(txtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)
                        .addComponent(txtCET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel40)
                        .addComponent(CboFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(CboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel33)
                            .addComponent(txtMora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(CboTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(txtIOF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel34)
                                .addComponent(txtCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel29)
                                .addComponent(Cbostatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel35)
                            .addComponent(txtLucros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(txtSAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(CboMargem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vigencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel2.setText("Dt.Inicio:");

        jLabel6.setText("Dt.Termino:");

        jLabel7.setText("Carencia de:");

        jLabel8.setText("Situaçao:");

        CboSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo", "Observaçao", "Em Analise", " " }));

        jLabel13.setText("Prazos:");

        jLabel17.setText("Indice de Correçao:");

        jLabel18.setText("Periodicidade do Pagamento:");

        CboPeridiocidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensal", "Bimestral", "Trimestral" }));
        CboPeridiocidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboPeridiocidadeActionPerformed(evt);
            }
        });

        jLabel19.setText("Valores de Entrada:");

        jLabel22.setText("Dt.Vencimento:");

        jLabel42.setText("Forma de Pagamento:");

        CboFormPg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleto", "PIX", "Debito da Conta ", "Cartao de Credito", "Cartao de Debito", "Deposito Bancario", "Link de Pagamento", "Hibrido", "Outros" }));

        jLabel43.setText("Tipo de Divida:");

        CboDivida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emprestimo", "Financiamento" }));

        jLabel44.setText("Conciliaçao:");

        CboConciliacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Conciliado", "Nao Conciliado", "Em processo de conciliação,", "Divergência encontrada,", "Conciliação parcial,", "Aguardando análise", "Rejeitado,", "Cancelado", "Devolvido", " " }));

        jLabel45.setText("Status:");

        CboVigStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        jLabel46.setText("Obsevaçoes:");

        jScrollPane2.setViewportView(txtPObsVig);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CboFormPg, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldDat, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CboDivida, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldDate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CboConciliacao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCarencia, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel44))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CboVigStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CboSituacao, javax.swing.GroupLayout.Alignment.LEADING, 0, 144, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrazos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CboPeridiocidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValores, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldVenc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrazos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboPeridiocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldVenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CboFormPg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboDivida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboConciliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboVigStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1510, 630));

        BtnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_excluir.png"))); // NOI18N
        BtnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancela, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 730, 80, 60));

        BtnSalva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnSalva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_salva.png"))); // NOI18N
        BtnSalva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSalva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalva, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 730, 80, 60));

        BtnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_impressora.png"))); // NOI18N
        getContentPane().add(BtnRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 730, 80, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaindoActionPerformed
        this.dispose();//volta a telaPrincipal
        TelaPrincipal.setVisible(true);
    }//GEN-LAST:event_BtnSaindoActionPerformed

    private void BtnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelaActionPerformed
        borrarFormMovimento();
        borrarFormVigencia();
    }//GEN-LAST:event_BtnCancelaActionPerformed

    private void BtnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvaActionPerformed
        
        Pesquisa p = new Pesquisa();
        p.setNome(txtNome.getText());
        p.setCPF(txtCPF.getText());
        p.setjFormattedTextFieldDta(jFormattedTextFieldDta.getText());
        
        Movimento m = new Movimento();
        m.setUN(txtUN.getText());
        m.setControle(txtControle.getText());
        m.setOperacao(txtOperacao.getText());
        m.setRenda(txtRenda.getText());
        m.setLimite(txtLimite.getText());
        m.setQuantia(txtQuantia.getText());
        m.setJuros(txtJuros.getText());
        m.setMulta(txtMulta.getText());
        m.setIOF(txtIOF.getText());
        m.setCredito(txtCredito.getText());
        m.setTaxas(txtTaxas.getText());
        m.setMora(txtMora.getText());
        m.setCapital(txtCapital.getText());
        m.setLucros(txtLucros.getText());
        m.setCapitalizacao(txtCapitalizacao.getText());
        m.setPagavel(txtPagavel.getText());
        m.setCodigo(txtCodigo.getText());
        m.setSAC(txtSAC.getText());
        m.setLblNomeCliente(lblNomeCliente.getText());
        m.setAvalista(txtAvalista.getText());
        String Tipo = (String) CboTipo.getSelectedItem();
        m.setTipo(Tipo);
        String Parcelas = (String) CboParcelas.getSelectedItem();
        m.setParcelas(Parcelas);
        String Margem = (String) CboMargem.getSelectedItem();
        m.setMargem(Margem);
        String TipoConta = (String) CboTipoConta.getSelectedItem();
        m.setTipoConta(TipoConta);
        String Status = (String) Cbostatus.getSelectedItem();
        m.setStatus(Status);
        String Fase = (String) CboFase.getSelectedItem();
        m.setFase(Fase);
        m.setObs(txtPObs.getText());
        
        Vigencia v = new Vigencia();
        v.setjFormattedTextFieldDat(jFormattedTextFieldDat.getText());
        v.setjFormattedTextFieldDate(jFormattedTextFieldDate.getText());
        v.setCarencia(txtCarencia.getText());
        v.setPrazos(txtPrazos.getText());
        v.setIndice(txtIndice.getText());
        v.setValores(txtValores.getText());
        v.setjFormattedTextFieldVenc(jFormattedTextFieldVenc.getText());
        String Situacao = (String) CboSituacao.getSelectedItem();
        v.setSituacao(Situacao);
        String Peridiocidade = (String) CboPeridiocidade.getSelectedItem();
        v.setPeridiocidade(Peridiocidade);
        String FormPg = (String) CboFormPg.getSelectedItem();
        v.setFormPg(FormPg);
        String Divida = (String) CboDivida.getSelectedItem();
        v.setDivida(Divida);
        String Conciliacao = (String) CboConciliacao.getSelectedItem();
        v.setConciliacao(Conciliacao);
        String VigStatus = (String) CboVigStatus.getSelectedItem();
        v.setVigStatus(VigStatus);
        v.setObsVig(txtPObsVig.getText());
        
        

        
        try (Connection conexao = Conexao.conectar()) {
        String sqlPesquisa = "INSERT INTO Pesquisa (nome, cpf, data) VALUES (?, ?, ?)";
        String sqlMovimento = "INSERT INTO Movimento "
        + "(un, controle, operacao, renda, limite, quantia, juros, multa, iof, credito, taxas, mora, capital, lucros, capitalizacao, pagavel, codigo, sac, lbl_nome_cliente, avalista, tipo, parcelas, margem, tipoConta, status, fase, obs) "
        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

         String sqlVigencia = "INSERT INTO Vigencia "
        + "(data_inicio, data_fim, carencia, prazos, indice, valores, vencimento, situacao, peridiocidade, FormPg, Divida, Conciliacao, VigStatus, ObsVig) "
        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try (PreparedStatement stmtPesq = conexao.prepareStatement(sqlPesquisa);
         PreparedStatement stmtMov = conexao.prepareStatement(sqlMovimento);
         PreparedStatement stmtVig = conexao.prepareStatement(sqlVigencia)) {

        stmtPesq.setString(1, p.getNome());
        stmtPesq.setString(2, p.getCPF());
        stmtPesq.setDate(3, java.sql.Date.valueOf(p.getjFormattedTextFieldDta())); //converte
        stmtPesq.executeUpdate();

        //MOVIMENTo
        stmtMov.setString(1, m.getUN());
        stmtMov.setString(2, m.getControle());
        stmtMov.setString(3, m.getOperacao());
        stmtMov.setString(4, m.getRenda());
        stmtMov.setString(5, m.getLimite());
        stmtMov.setString(6, m.getQuantia());
        stmtMov.setString(7, m.getJuros());
        stmtMov.setString(8, m.getMulta());
        stmtMov.setString(9, m.getIOF());
        stmtMov.setString(10, m.getCredito());
        stmtMov.setString(11, m.getTaxas());
        stmtMov.setString(12, m.getMora());
        stmtMov.setString(13, m.getCapital());
        stmtMov.setString(14, m.getLucros());
        stmtMov.setString(15, m.getCapitalizacao());
        stmtMov.setString(16, m.getPagavel());
        stmtMov.setString(17, m.getCodigo());
        stmtMov.setString(18, m.getSAC());
        stmtMov.setString(19, m.getLblNomeCliente());
        stmtMov.setString(20, m.getAvalista());
        stmtMov.setString(21, m.getTipo());
        stmtMov.setString(22, m.getParcelas());
        stmtMov.setString(23, m.getMargem());
        stmtMov.setString(24, m.getTipoConta());
        stmtMov.setString(25, m.getStatus());
        stmtMov.setString(26, m.getFase());
        stmtMov.setString(27, m.getObs());
        stmtMov.executeUpdate();
        
        //VIGENCIA
        
        
        stmtVig.setDate(1, java.sql.Date.valueOf(v.getjFormattedTextFieldDat()));
        stmtVig.setDate(2, java.sql.Date.valueOf(v.getjFormattedTextFieldDate()));
        stmtVig.setString(3, v.getCarencia());
        stmtVig.setString(4, v.getPrazos());
        stmtVig.setString(5, v.getIndice());
        stmtVig.setString(6, v.getValores());
        stmtVig.setDate(7, java.sql.Date.valueOf(v.getjFormattedTextFieldVenc()));
        stmtVig.setString(8, v.getSituacao());
        stmtVig.setString(9, v.getPeridiocidade());
        stmtVig.setString(10, v.getFormPg());
        stmtVig.setString(11, v.getDivida());
        stmtVig.setString(12, v.getConciliacao());
        stmtVig.setString(13, v.getVigStatus());
        stmtVig.setString(14, v.getObsVig());
        
        stmtVig.executeUpdate();

        JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!");
        borrarFormMovimento();
        borrarFormVigencia();
    }
    } catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Erro ao salvar os dados: " + e.getMessage());
   }
    }//GEN-LAST:event_BtnSalvaActionPerformed

    private void BtnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisaActionPerformed
        String cpf = txtCPF.getText();

    if (cpf.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, insira o CPF para pesquisa.");
        return;
    }

    Pesquisa cliente = BuscarClienteporCPF(cpf);

    if (cliente != null) {
        txtNome.setText(cliente.getNome());
        txtCPF.setText(cliente.getCPF());
        jFormattedTextFieldDta.setText(cliente.getjFormattedTextFieldDta());
        lblNomeCliente.setText(cliente.getNome());
        // Preencha outros campos conforme necessário
        JOptionPane.showMessageDialog(this, "Cliente encontrado!");
    } else {
        JOptionPane.showMessageDialog(this, "Cliente não encontrado no sistema.");
    }
    }//GEN-LAST:event_BtnPesquisaActionPerformed

    private void CboPeridiocidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboPeridiocidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboPeridiocidadeActionPerformed

    private void lblNomeClienteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblNomeClienteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomeClienteAncestorAdded

    public Pesquisa BuscarClienteporCPF(String CPF){
    Pesquisa cliente = null;
    String sql = "SELECT * FROM Cadastro_pessoal WHERE cpf = ?";

    try (Connection conexao = Conexao.conectar();
         PreparedStatement stmt = conexao.prepareStatement(sql)) {
        stmt.setString(1, CPF);

        try (ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                cliente = new Pesquisa();
                cliente.setNome(rs.getString("nome_completo"));
                cliente.setCPF(rs.getString("cpf"));
                cliente.setjFormattedTextFieldDta(rs.getString("data_nascimento"));
                // Preencha outros campos, se necessário
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Erro ao buscar cliente: " + e.getMessage());
    }

    return cliente;
    }
    
    public void borrarFormMovimento(){
        txtUN.setText("");
        txtControle.setText("");
        txtOperacao.setText("");
        txtRenda.setText("");
        txtLimite.setText("");
        txtQuantia.setText("");
        txtJuros.setText("");
        txtMulta.setText("");
        txtIOF.setText("");
        txtCredito.setText("");
        txtTaxas.setText("");
        txtCET.setText("");
        txtMora.setText("");
        txtCapital.setText("");
        txtLucros.setText("");
        txtCapitalizacao.setText("");
        txtPagavel.setText("");
        txtCodigo.setText("");
        txtSAC.setText("");
        txtAvalista.setText("");
        txtPObs.setText("");
    }
    public void borrarFormVigencia(){
        txtCarencia.setText("");
        txtPrazos.setText("");
        txtIndice.setText("");
        txtValores.setText("");
        jFormattedTextFieldDat.setText("");//inicio
        jFormattedTextFieldDate.setText("");//termino
        jFormattedTextFieldVenc.setText("");//vencimento
        txtPObsVig.setText("");//campo de observaçoes
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmprestimoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmprestimoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmprestimoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmprestimoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmprestimoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancela;
    private javax.swing.JButton BtnPesquisa;
    private javax.swing.JButton BtnRelatorio;
    private javax.swing.JButton BtnSaindo;
    private javax.swing.JButton BtnSalva;
    private javax.swing.JComboBox<String> CboConciliacao;
    private javax.swing.JComboBox<String> CboDivida;
    private javax.swing.JComboBox<String> CboFase;
    private javax.swing.JComboBox<String> CboFormPg;
    private javax.swing.JComboBox<String> CboMargem;
    private javax.swing.JComboBox<String> CboParcelas;
    private javax.swing.JComboBox<String> CboPeridiocidade;
    private javax.swing.JComboBox<String> CboSituacao;
    private javax.swing.JComboBox<String> CboTipo;
    private javax.swing.JComboBox<String> CboTipoConta;
    private javax.swing.JComboBox<String> CboVigStatus;
    private javax.swing.JComboBox<String> Cbostatus;
    private javax.swing.JFormattedTextField jFormattedTextFieldDat;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate;
    private javax.swing.JFormattedTextField jFormattedTextFieldDta;
    private javax.swing.JFormattedTextField jFormattedTextFieldVenc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JTextField txtAvalista;
    private javax.swing.JTextField txtCET;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCapital;
    private javax.swing.JTextField txtCapitalizacao;
    private javax.swing.JTextField txtCarencia;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtControle;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtIOF;
    private javax.swing.JTextField txtIndice;
    private javax.swing.JTextField txtJuros;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextField txtLucros;
    private javax.swing.JTextField txtMora;
    private javax.swing.JTextField txtMulta;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtOperacao;
    private javax.swing.JTextPane txtPObs;
    private javax.swing.JTextPane txtPObsVig;
    private javax.swing.JTextField txtPagavel;
    private javax.swing.JTextField txtPrazos;
    private javax.swing.JTextField txtQuantia;
    private javax.swing.JTextField txtRenda;
    private javax.swing.JTextField txtSAC;
    private javax.swing.JTextField txtTaxas;
    private javax.swing.JTextField txtUN;
    private javax.swing.JTextField txtValores;
    // End of variables declaration//GEN-END:variables
}
